language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '11'
script:
  - npm run test -- --coverage
deploy:
  provider: script
  script: npm run deploy:ci
  skip_cleanup: true
  on:
    branch: release
